services:
  app:
    build:
      context: .
      args:
        JDK_VERSION: "21"
        MAVEN_OPTS: "-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2"
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/marketmaker
      SPRING_DATASOURCE_USERNAME: mmbot
      SPRING_DATASOURCE_PASSWORD: HcOToDCCFI1ZG5tPRrMu
      # You can also inject Zano endpoint here if your app needs it
      # ZANO_RPC_URL: http://zanod:11211
    depends_on:
      - mariadb
      - zanod
    networks: [backend]

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: marketmaker
      MYSQL_USER: mmbot
      MYSQL_PASSWORD: HcOToDCCFI1ZG5tPRrMu
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [backend]

  zanod:
    image: canardleteer/zano:2.1.9.431-zanod-distroless
    container_name: zanod
    command:
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=11211
      # Optional extras:
      # - --enable-offers-service
      # - --hide-my-port
    tty: true
    restart: unless-stopped
    volumes:
      - ./zano-data:/home/nonroot/.Zano:Z
    expose:
      - "11211"     # RPC available only inside Docker network
    ports:
      - "11321:11121" # P2P inbound
      - "11311:11211"
    networks: [backend]

  zanowallet-init:
    image: canardleteer/zano:2.1.9.431-simplewallet-distroless
    command:
      - --generate-new-wallet=/home/nonroot/wallet/mywallet.wallet
      - --password=mysecurepassword
    volumes:
      - ./zano-wallet:/home/nonroot/wallet:Z
    networks: [backend]
    restart: "no"   # run once, exit

  zanowallet:
    image: canardleteer/zano:2.1.9.431-simplewallet-distroless
    depends_on:
      - zanowallet-init
    container_name: zanowallet
    command:
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=11212
      - --password=mysecurepassword
      - --wallet-file=/home/nonroot/wallet/mywallet.wallet
      - --daemon-address=zanod:11211
      # Optional extras:
      # - --enable-offers-service
      # - --hide-my-port
    tty: true
    restart: unless-stopped
    volumes:
      - ./zano-wallet:/home/nonroot/wallet:Z
    expose:
      - "11212"     # RPC available only inside Docker network
    networks: [backend]

volumes:
  mariadb_data:
  zano_chain:

networks:
  backend:
    driver: bridge
