// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public interface PublicBookTickerV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicBookTickerV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bidPrice = 1;</code>
   * @return The bidPrice.
   */
  java.lang.String getBidPrice();
  /**
   * <code>string bidPrice = 1;</code>
   * @return The bytes for bidPrice.
   */
  com.google.protobuf.ByteString
      getBidPriceBytes();

  /**
   * <code>string bidQuantity = 2;</code>
   * @return The bidQuantity.
   */
  java.lang.String getBidQuantity();
  /**
   * <code>string bidQuantity = 2;</code>
   * @return The bytes for bidQuantity.
   */
  com.google.protobuf.ByteString
      getBidQuantityBytes();

  /**
   * <code>string askPrice = 3;</code>
   * @return The askPrice.
   */
  java.lang.String getAskPrice();
  /**
   * <code>string askPrice = 3;</code>
   * @return The bytes for askPrice.
   */
  com.google.protobuf.ByteString
      getAskPriceBytes();

  /**
   * <code>string askQuantity = 4;</code>
   * @return The askQuantity.
   */
  java.lang.String getAskQuantity();
  /**
   * <code>string askQuantity = 4;</code>
   * @return The bytes for askQuantity.
   */
  com.google.protobuf.ByteString
      getAskQuantityBytes();
}
