// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicIncreaseDepthsV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public final class PublicIncreaseDepthsV3ApiProto {
  private PublicIncreaseDepthsV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicIncreaseDepthsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicIncreaseDepthsV3Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicIncreaseDepthV3ApiItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicIncreaseDepthV3ApiItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037PublicIncreaseDepthsV3Api.proto\"\231\001\n\031Pu" +
      "blicIncreaseDepthsV3Api\022+\n\004asks\030\001 \003(\0132\035." +
      "PublicIncreaseDepthV3ApiItem\022+\n\004bids\030\002 \003" +
      "(\0132\035.PublicIncreaseDepthV3ApiItem\022\021\n\teve" +
      "ntType\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\"?\n\034PublicI" +
      "ncreaseDepthV3ApiItem\022\r\n\005price\030\001 \001(\t\022\020\n\010" +
      "quantity\030\002 \001(\tBB\n\034com.mxc.push.common.pr" +
      "otobufB\036PublicIncreaseDepthsV3ApiProtoH\001" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicIncreaseDepthsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicIncreaseDepthsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicIncreaseDepthsV3Api_descriptor,
        new java.lang.String[] { "Asks", "Bids", "EventType", "Version", });
    internal_static_PublicIncreaseDepthV3ApiItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicIncreaseDepthV3ApiItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicIncreaseDepthV3ApiItem_descriptor,
        new java.lang.String[] { "Price", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
