// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicLimitDepthsV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public interface PublicLimitDepthV3ApiItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicLimitDepthV3ApiItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  java.lang.String getQuantity();
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();
}
