// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public final class PublicBookTickerV3ApiProto {
  private PublicBookTickerV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicBookTickerV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicBookTickerV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PublicBookTickerV3Api.proto\"e\n\025PublicB" +
      "ookTickerV3Api\022\020\n\010bidPrice\030\001 \001(\t\022\023\n\013bidQ" +
      "uantity\030\002 \001(\t\022\020\n\010askPrice\030\003 \001(\t\022\023\n\013askQu" +
      "antity\030\004 \001(\tB>\n\034com.mxc.push.common.prot" +
      "obufB\032PublicBookTickerV3ApiProtoH\001P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicBookTickerV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicBookTickerV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicBookTickerV3Api_descriptor,
        new java.lang.String[] { "BidPrice", "BidQuantity", "AskPrice", "AskQuantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
