// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicIncreaseDepthsBatchV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public interface PublicIncreaseDepthsBatchV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicIncreaseDepthsBatchV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  java.util.List<com.mxc.push.common.protobuf.PublicIncreaseDepthsV3Api> 
      getItemsList();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicIncreaseDepthsV3Api getItems(int index);
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  java.util.List<? extends com.mxc.push.common.protobuf.PublicIncreaseDepthsV3ApiOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .PublicIncreaseDepthsV3Api items = 1;</code>
   */
  com.mxc.push.common.protobuf.PublicIncreaseDepthsV3ApiOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();
}
