// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerBatchV3Api.proto

// Protobuf Java Version: 3.25.6
package com.mxc.push.common.protobuf;

public final class PublicBookTickerBatchV3ApiProto {
  private PublicBookTickerBatchV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicBookTickerBatchV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n PublicBookTickerBatchV3Api.proto\032\033Publ" +
      "icBookTickerV3Api.proto\"C\n\032PublicBookTic" +
      "kerBatchV3Api\022%\n\005items\030\001 \003(\0132\026.PublicBoo" +
      "kTickerV3ApiBC\n\034com.mxc.push.common.prot" +
      "obufB\037PublicBookTickerBatchV3ApiProtoH\001P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mxc.push.common.protobuf.PublicBookTickerV3ApiProto.getDescriptor(),
        });
    internal_static_PublicBookTickerBatchV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicBookTickerBatchV3Api_descriptor,
        new java.lang.String[] { "Items", });
    com.mxc.push.common.protobuf.PublicBookTickerV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
